services:
  backend:
    build: .
    container_name: guesthouse-backend
    restart: always
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - OAUTH2_REDIRECT_BASE_URL=${OAUTH2_REDIRECT_BASE_URL}
      - OAUTH2_FRONTEND_BASE_URL=${OAUTH2_FRONTEND_BASE_URL}
      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
    extra_hosts:
      - "host.docker.internal:host-gateway"
