services:
  redis:
    image: redis:7-alpine
    container_name: guesthouse-redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - mysql_default
    command: redis-server --appendonly yes

  backend:
    # build: .
    image: lkm011/guesthouse-backend:latest
    pull_policy: always
    container_name: guesthouse-backend
    restart: always
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - REDIS_HOST=redis
      - GOOGLE_CLOUD_CREDENTIALS_LOCATION=file:/app/googlevision/ocr-test-480914-b8a930bfbdc0.json
    volumes:
      - ./googlevision:/app/googlevision
    networks:
      - mysql_default
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - redis

networks:
  mysql_default:
    external: true
